ci: update docker-publish

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -49,6 +49,23 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
 
+      - name: Read version
+        run: |
+          if [ ! -f .version ]; then
+            echo "::error::.version file not found."
+            exit 1
+          fi
+
+          VERSION=$(grep '^VERSION=' .version | cut -d'=' -f2 | tr -d '[:space:]')
+
+          if [ -z "$VERSION" ]; then
+            echo "::error::VERSION not found in .version"
+            exit 1
+          fi
+
+          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
+          echo "Docker image version: $VERSION"
+
       - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
@@ -66,4 +83,4 @@ jobs:
           push: true
           tags: |
             ${{ vars.DOCKER_HUB_USERNAME }}/nq-api:latest
-            ${{ vars.DOCKER_HUB_USERNAME }}/nq-api:${{ github.ref_name }}
+            ${{ vars.DOCKER_HUB_USERNAME }}/nq-api:${{ env.VERSION }}
